#!/bin/bash

if [[ $MARIADB_PASS != "NONE" ]]; then
    MARIADB_PASS=${MARIADB_PASS:-"$(pwgen -B -s 24 1)"}
fi

mkdir -p /data/db /data/logs/supervisor
chown -R mysql:mysql /data/db

if [ ! "$(ls -A /data/db)" ]; then
    mysql_install_db --datadir=/data/db --user=mysql
    mysqld_safe --skip-grant-tables &

    printf "\nWaiting for DB daemon started.."
    while [ ! -e /var/run/mysqld/mysqld.sock ]; do
        printf "."
        sleep 2
    done
    echo "DB daemon started!"

    printf "Creating DB user.."
    mysql -u root -e "FLUSH PRIVILEGES; CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASS'; GRANT ALL PRIVILEGES ON *.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;"
    if [[ $MARIADB_DB != "NONE" ]]; then
        mysql -u "$MARIADB_USER" -p"$MARIADB_PASS" -e "CREATE DATABASE $MARIADB_DB;"
    fi
    mysqladmin -u "$MARIADB_USER" -p"$MARIADB_PASS" shutdown
    echo "MariaDB Username: $MARIADB_USER"
    echo "MariaDB Password: $MARIADB_PASS"
fi
