#!/bin/bash

printf "\n\n### Building container: nematix/ubuntu\n"
docker build --rm -t "nematix/ubuntu" ubuntu

printf "\n\n### Building container: nematix/data\n"
docker build --rm -t "nematix/data" data
