#!/bin/bash

printf "\n\n### Building container: nematix/composer\n"
docker build --rm -t "nematix/composer" composer

printf "\n\n### Building container: nematix/laravel-artisan\n"
docker build --rm -t "nematix/laravel-artisan" laravel-artisan
